name: pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BUILD
        run: echo "RUNNING BUILD"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: echo "RUNNING TEST"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY
        run: echo "RUNNING DEPLOY"
  
